export const SET_HOUSES_DATA = "SET_HOUSES_DATA";
export const SET_OPTION = "SET_OPTION";
export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB";
export const TOGGLE_HOUSE_BUILDER = "TOGGLE_HOUSE_BUILDER";
export const SET_ACTIVE_HOUSE_CATEGORY_TAB = "SET_ACTIVE_HOUSE_CATEGORY_TAB";